### ISSUE TITLE
Getting contract details fails with the official W-9 template

### ISSUE THREAD

**Issue by mmrazik** [docusign/docusign-ruby-client#40] opened 2020-05-12 14:23 UTC
I used the W-9 template from template library: https://support.docusign.com/knowledgemarket/Template-Library-W-9 to send a contract.

Now when I am trying to get the envelope I am getting the following exception:
`*** NoMethodError Exception: undefined method 'build_from_hash' for []:Array`

This is the top of the stack trace:
```
[  0] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb:502:in `_deserialize'",
    [  1] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb:454:in `block (2 levels) in build_from_hash'",
    [  2] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb:454:in `map'",
    [  3] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb:454:in `block in build_from_hash'",
    [  4] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb:449:in `each_pair'",
    [  5] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb:449:in `build_from_hash'",
    [  6] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/signer.rb:999:in `_deserialize'",
    [  7] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/signer.rb:954:in `block in build_from_hash'",
    [  8] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/signer.rb:946:in `each_pair'",
    [  9] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/signer.rb:946:in `build_from_hash'",
    [ 10] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/recipients.rb:267:in `_deserialize'",
    [ 11] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/recipients.rb:219:in `block (2 levels) in build_from_hash'",
    [ 12] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/recipients.rb:219:in `map'",
    [ 13] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/recipients.rb:219:in `block in build_from_hash'",
    [ 14] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/recipients.rb:214:in `each_pair'",
    [ 15] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/recipients.rb:214:in `build_from_hash'",
    [ 16] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/envelope.rb:878:in `_deserialize'",
    [ 17] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/envelope.rb:833:in `block in build_from_hash'",
    [ 18] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/envelope.rb:825:in `each_pair'",
    [ 19] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/envelope.rb:825:in `build_from_hash'",
    [ 20] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/client/api_client.rb:217:in `block in convert_to_type'",
    [ 21] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/client/api_client.rb:216:in `tap'",
    [ 22] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/client/api_client.rb:216:in `convert_to_type'",
    [ 23] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/client/api_client.rb:177:in `deserialize'",
    [ 24] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/client/api_client.rb:76:in `call_api'",
    [ 25] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/api/envelopes_api.rb:3229:in `get_envelope_with_http_info'",
    [ 26] "/home/toptal/staging.toptal.net/shared/bundle/ruby/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/api/envelopes_api.rb:3192:in `get_envelope'",
```

In debugger it looks like this (seems like it is the drop-down list of states that is causing trouble):
```
[497, 506] in /home/mmrazik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb
   497:             hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
   498:           end
   499:         end
   500:       else # model
   501:         debugger
=> 502:         temp_model = DocuSign_eSign.const_get(type).new
   503:         temp_model.build_from_hash(value)
   504:       end
   505:     end
   506: 
(byebug) type
"Array"
(byebug) next

[498, 507] in /home/mmrazik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/docusign_esign-3.2.1/lib/docusign_esign/models/tabs.rb
   498:           end
   499:         end
   500:       else # model
   501:         debugger
   502:         temp_model = DocuSign_eSign.const_get(type).new
=> 503:         temp_model.build_from_hash(value)
   504:       end
   505:     end
   506: 
   507:     # Returns the string representation of the object
(byebug) temp_model
[]
(byebug) value
{:listItems=>[{:text=>"AL", :value=>"AL", :selected=>"false"}, {:text=>"AK", :value=>"AK", :selected=>"false"}, {:text=>"AZ", :value=>"AZ", :selected=>"false"}, {:text=>"AR", :value=>"AR", :selected=>"false"}, {:text=>"CA", :value=>"CA", :selected=>"false"}, {:text=>"CO", :value=>"CO", :selected=>"false"}, {:text=>"CT", :value=>"CT", :selected=>"false"}, {:text=>"DE", :value=>"DE", :selected=>"false"}, {:text=>"FL", :value=>"FL", :selected=>"false"}, {:text=>"GA", :value=>"GA", :selected=>"false"}, {:text=>"HI", :value=>"HI", :selected=>"false"}, {:text=>"ID", :value=>"ID", :selected=>"false"}, {:text=>"IL", :value=>"IL", :selected=>"false"}, {:text=>"IN", :value=>"IN", :selected=>"false"}, {:text=>"IA", :value=>"IA", :selected=>"false"}, {:text=>"KS", :value=>"KS", :selected=>"false"}, {:text=>"KY", :value=>"KY", :selected=>"false"}, {:text=>"LA", :value=>"LA", :selected=>"false"}, {:text=>"ME", :value=>"ME", :selected=>"false"}, {:text=>"MD", :value=>"MD", :selected=>"false"}, {:text=>"MA", :value=>"MA", :selected=>"false"}, {:text=>"MI", :value=>"MI", :selected=>"false"}, {:text=>"MN", :value=>"MN", :selected=>"false"}, {:text=>"MS", :value=>"MS", :selected=>"false"}, {:text=>"MO", :value=>"MO", :selected=>"false"}, {:text=>"MT", :value=>"MT", :selected=>"false"}, {:text=>"NE", :value=>"NE", :selected=>"false"}, {:text=>"NV", :value=>"NV", :selected=>"false"}, {:text=>"NH", :value=>"NH", :selected=>"false"}, {:text=>"NJ", :value=>"NJ", :selected=>"false"}, {:text=>"NM", :value=>"NM", :selected=>"false"}, {:text=>"NY", :value=>"NY", :selected=>"false"}, {:text=>"NC", :value=>"NC", :selected=>"false"}, {:text=>"ND", :value=>"ND", :selected=>"false"}, {:text=>"OH", :value=>"OH", :selected=>"false"}, {:text=>"OK", :value=>"OK", :selected=>"false"}, {:text=>"OR", :value=>"OR", :selected=>"false"}, {:text=>"PA", :value=>"PA", :selected=>"false"}, {:text=>"RI", :value=>"RI", :selected=>"false"}, {:text=>"SC", :value=>"SC", :selected=>"false"}, {:text=>"SD", :value=>"SD", :selected=>"false"}, {:text=>"TN", :value=>"TN", :selected=>"false"}, {:text=>"TX", :value=>"TX", :selected=>"false"}, {:text=>"UT", :value=>"UT", :selected=>"false"}, {:text=>"VT", :value=>"VT", :selected=>"false"}, {:text=>"VA", :value=>"VA", :selected=>"false"}, {:text=>"WA", :value=>"WA", :selected=>"false"}, {:text=>"WV", :value=>"WV", :selected=>"false"}, {:text=>"WI", :value=>"WI", :selected=>"false"}, {:text=>"WY", :value=>"WY", :selected=>"false"}], :value=>"", :shared=>"false", :requireInitialOnSharedChange=>"false", :required=>"true", :locked=>"false", :requireAll=>"false", :tabLabel=>"W9 State", :font=>"arial", :fontColor=>"black", :fontSize=>"size9", :localePolicy=>{}, :documentId=>"1", :recipientId=>"1", :pageNumber=>"1", :xPosition=>"240", :yPosition=>"237", :width=>"78", :height=>"9", :tabId=>"290b1cbe-5e20-461f-8fbc-fbf41c52decd", :templateRequired=>"false", :tabType=>"list"}
(byebug) temp_model.build_from_hash(value)
*** NoMethodError Exception: undefined method `build_from_hash' for []:Array
```

**Comment by gsnavin** [comment] 2020-05-28 05:46
@mmrazik sorry you are running into this issue. could you please share the code snippet you are running so I can try reproduce it?

**Comment by LarryKlugerDS** [comment] 2020-06-07 08:03
Hi @mmrazik , Is this still an issue? Can you try out the new version of the Ruby SDK to see if it solves it? 
Thank you,
Larry

**Comment by LarryKlugerDS** [comment] 2020-07-15 14:31
Closing--no reply since Jun 7. Please respond if this is still an issue. Thank you.

**Closed by LarryKlugerDS** 2020-07-15 14:31 UTC
Labels: question

**Comment by LyricL-Gitster** [comment] 2021-03-17 15:22
Just ran into this same issue on `3.8.0.rc1` calling `get_document_tabs`.
