### ISSUE TITLE
Allow passing in JWT

### ISSUE THREAD

**Issue by vcsjones** [docusign/docusign-ruby-client#7] opened 2018-03-27 21:55 UTC
This line:

https://github.com/docusign/docusign-ruby-client/blob/c69e4785115a2ed4eb716f9af216454f93ae8971/lib/docusign_esign/api_client.rb#L386

Wants you to pass in a path to the RSA secret as a file on disk. We would prefer to pass in the JWT ourselves, or barring that an instance of `OpenSSL::PKey::RSA` so that we can source our private key from somewhere other than a file on disk.

PR #5 would probably be sufficient for us, for now, but also somewhat less ideal. If we can pass in an instance of `OpenSSL::PKey::RSA` or the JWT, then allows many options, such as HSM or other key-in-hardware solutions.

**Comment by LarryKlugerDS** [comment] 2018-03-28 08:06
Hi,

Thank you for raising the issue. We, DocuSIgn, agree, and have the change on our roadmap. Internal issue DCM-2274.

I appreciate your offer to do a pull request. I am not sure if that part of the SDK is controlled by the Swagger CodeGen app or not. (I will ask.) If it is covered by Swagger Code Gen then we need to change the generator.

**Comment by LarryKlugerDS** [comment] 2019-03-17 11:25
Update: DCM-2312 is the Ruby SDK-specific ticket.

**Comment by gustavomazzoni** [comment] 2019-05-03 15:58
Any update? This is an easy, straightforward change.

**Comment by LarryKlugerDS** [comment] 2019-09-02 12:29
I apologize for my slow reply. The issue is still in plan, but awaiting resources. Unfortunately, at this time, I don't yet have a schedule date.

**Comment by LarryKlugerDS** [comment] 2019-10-08 11:56
Good news, this issue has been fixed with the 3.0.0.rc.1 release of the SDK and [gem](https://rubygems.org/gems/docusign_esign/versions/3.0.0.rc1). The source is available as branch [ngopala/v2.1-19.2.02](https://github.com/docusign/docusign-ruby-client/tree/ngopala/v2.1-19.2.02). 

It will be released to master and the gem will be updated in the next week.

Please comment on this issue if you spot any issues with the RC (release candidate) or the forthcoming release.

Thanks,
Larry

**Closed by LarryKlugerDS** 2019-10-08 11:56 UTC
Labels: DCM-2312
